Cobaform/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('blog/',include('blog.urls',namespace='blog')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('',views.create,name='create'),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),

]

blog/urls.py
from . import views
from django.urls import path

app_name='blog' #utk url di home & contact
urlpatterns=[
    path('create/',views.create,name='create'),
    path('',views.index,name='index'),
]

contact/urls.py
from django.urls import path
from . import views

app_name='contact' #utk url di home & contact
urlpatterns=[
    path('',views.index,name='index')
]

blog/models.py
from django.db import models

# Create your models here.
class BlogModel(models.Model):
    judul = models.CharField(max_length=20)
    body = models.TextField()
    category = models.CharField(max_length=20)
def __str__ (self):
    return "{}.{}".format(self.id, self.judul)

contact/models.py
from django.db import models

# Create your models here.

Cobaform/forms.py
from django import forms

class HomeForm(forms.Form):
    nama_lengkap = forms.CharField(
        label ='Nama Lengkap',
        widget =forms.TextInput(attrs={'class':'form-control', 'placeholder':"Masukkan Nama Lengkap"})
    )
    category = forms.CharField(
        label = 'Category',
        widget = forms.TextInput(attrs={'class':'form-control'})
    )

blog/forms.py
from django import forms

class BlogForm(forms.Form):
    judul = forms.CharField(
        label ='Judul',
        widget =forms.TextInput(attrs={'class':'form-control', 'placeholder':"Masukkan Judul"})
    )
    body = forms.CharField(
        label = 'Body',
        widget = forms.Textarea(attrs={'class':'form-control'})
    )
    category = forms.CharField(
        label = 'Category',
        widget = forms.TextInput(attrs={'class':'form-control'})
    )

    def clean_judul(self):
        judul_input = self.cleaned_data.get('judul')
        if judul_input == 'ucup':
            raise forms.ValidationError("Ucup tdk boleh diposting")
        return judul_input

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    #data type
    integer   = forms.IntegerField()
    decimal   = forms.DecimalField()
    float     = forms.FloatField()
    boolean   = forms.BooleanField()
    character = forms.CharField(widget=forms.Textarea)
    #string type
    email   = forms.EmailField()
        # regex_field   = forms.RegexField()
    slug    = forms.SlugField()
    url     = forms.URLField()
        # ip      = forms.GenericIPAddressfield()
    #select input
    PILIHAN = (
        ('pilih1','nilai 1'),
        ('pilih2','nilai 2'),
        ('pilih3','nilai 3'),
    )
    choice = forms.ChoiceField(choices=PILIHAN)
    multiple_choice = forms.MultipleChoiceField(choices=PILIHAN)
    multi_type = forms.TypedMultipleChoiceField(choices=PILIHAN)
    #date time
    #file input
    file = forms.FileField()
    img = forms.ImageField()

    

Cobaform/views.py
from django.shortcuts import render
from .forms import HomeForm

def index (request):
    context={
    'heading':'List Post'
    }
    return render (request, "index.html",context)

def create (request):
    cont_form= HomeForm()
    if request.method == 'POST':
        print (request, 'POST')
    context={
    'heading':'Create Post',
    'contact_form':cont_form,
    }
    return render (request, "create.html",context)

blog/views.py
from django.shortcuts import render, redirect
from .forms import BlogForm
from .models import BlogModel

# Create your views here.
def index (request):

    posts = BlogModel.objects.all()

    context={
    'heading':'List Post',
    'post':posts
    }

    return render (request, "blog/index.html",context)

def create (request):
    cont_form= BlogForm(request.POST)

    if request.method == 'POST':
        if cont_form.is_valid():
            BlogModel.objects.create( #tanpa ini, harus dibawah context
                #cara dibawah ambil ambil data yg sudah divalidasi, bukan raw lagi
                judul    = cont_form.cleaned_data.get('judul'), #context['judul'] = request.POST['judul'],
                body     = cont_form.cleaned_data.get('body'), #context['body'] = request.POST['body'],
                category = cont_form.cleaned_data.get('category'), #context['category'] = request.POST['category'],
            )

            return redirect ("/blog/")

    context={
    'heading':'Create Post',
    'contact_form':cont_form,
    }

    return render (request, "blog/create.html",context)

contact/views.py
from django.shortcuts import render
from .forms import ContactForm #or from . import forms (dibelakang fungsi ditambah forms.)
# Create your views here.

def index (request):
    cont_form= ContactForm()
    context={
    'heading':'Ini Heading Contact',
    'contact_form':cont_form,
    }
    return render (request, "contact/contact.html",context)

blog/templates/blog/create.html
{%extends "base.html"%}

{%block title%}
  {{heading}}
{%endblock title%}

{%block content%}
  <form method="post">
    {%csrf_token%}
    <div class="form-group">
      {{contact_form.judul.label_tag}}
      {{contact_form.judul}}
      {{contact_form.body.label_tag}}
      {{contact_form.body}}
      {{contact_form.category.label_tag}}
      {{contact_form.category}}
    </div>

    <button type="submit" name="button">Submit</button>
  </form>
{%endblock content%}

blog/templates/blog/index.html
{%extends "base.html"%}

{%block title%}
  {{heading}}
{%endblock title%}

{%block content%}
  <h1>{{heading}}</h1>
  {%for i in post%}
   <h1>{{i.judul}}</h1>
   <p>{{i.body}}</p>
   <p>{{i.category}}</p>
  {%endfor%}
{%endblock content%}

contact/templates/contact/contact.html
{%extends "base.html"%}

{%block title%}
  {{heading}}
{%endblock title%}

{%block content%}
  <form method="post">
    {%csrf_token%}
    <table>
    {{contact_form.as_table}}
    </table>
    <button type="submit" name="button">Submit</button>
  </form>
{%endblock content%}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {%block title%}

      {%endblock title%}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <div class="container">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" href="{%url 'index'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'contact:index'%}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'blog:index'%}">Blog</a>
          <ul>
            <li>  <a class="nav-link" href="{%url 'blog:create'%}">Create</a></li>
          </ul>
        </li>
      </ul>

      {%block content%}

      {%endblock content%}
    </div>

  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/create.html
{%extends "base.html"%}

{%block title%}
  {{heading}}
{%endblock title%}

{%block content%}
  <form method="post">
    {%csrf_token%}
    <div class="form-group">
      {{contact_form.nama_lengkap.label_tag}}
      {{contact_form.nama_lengkap}}
      {{contact_form.category.label_tag}}
      {{contact_form.category}}
    </div>

    <button type="submit" name="button">Submit</button>
  </form>
{%endblock content%}

templates/index.html
{%extends "base.html"%}

{%block title%}
  {{heading}}
{%endblock title%}

{%block content%}

  <p>{{heading}}</p>
  <p>edit di local</p>
  <p>edit dari lokal</p>

{%endblock content%}